Rename containers 2
FlowFuse/docker-compose pull request #117
Opened 2024-01-11 09:21 UTC by hardillb

part of FlowFuse/admin#212

## Description

Not to be merged before #116 

## Related Issue(s)

FlowFuse/admin#212

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] Suitable unit/system level tests have been added and they pass 
 - [ ] Documentation has been updated
    - [ ] Upgrade instructions
    - [ ] Configuration details
    - [ ] Concepts
 - [ ] Changes `flowforge.yml`?
    - [ ] Issue/PR raised on `FlowFuse/helm` to update ConfigMap Template
    - [ ] Issue/PR raised on `FlowFuse/CloudProject` to update values for Staging/Production

## Labels

 - [ ] Backport needed? -> add the `backport` label
 - [ ] Includes a DB migration? -> add the `area:migration` label

2024-01-16 09:16 UTC, knolleary requested changes
FlowFuse org on dockerhub has its own set of credentials

2024-02-16 10:45 UTC, hardillb commented
This is still showing changes that are already merged into the build-containers.yml action file.

2024-02-16 11:28 UTC, ppawlowski approved these changes

2024-02-19 09:38 UTC, hardillb commented
@knolleary When you get a second can you review this please.

2024-02-19 09:42 UTC, knolleary approved these changes

2024-02-19 09:45 UTC, merged